'use strict';
const {
  Model
} = require('sequelize');
const creditcardGenerator = require('creditcard-generator');

module.exports = (sequelize, DataTypes) => {
  class Card extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
      models.Card.belongsTo(models.Wallet);
      models.Card.belongsTo(models.User);
    }
    static generateCardNumber(type) {
      const creditcards = creditcardGenerator.GenCC(type);
      return creditcards[0];
    }
    static generateRandomCCV() {
      return Math.floor(Math.random() * (999 - 1)) + 0;
    }
  };

  /**
   * Ideally the Expiration Date + Card Number can be generated by postgres.
   */
  Card.init({
    balance: DataTypes.INTEGER,
    walletId: DataTypes.INTEGER,
    currency: DataTypes.ENUM('usd', 'gbp', 'eur'),
    company: DataTypes.STRING,
    cardNumber: DataTypes.STRING,
    expirationDate: DataTypes.DATE,
    ccv: DataTypes.INTEGER,
    status: DataTypes.BOOLEAN
  }, {
    sequelize,
    modelName: 'Card',
  });
  return Card;
};